[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
regex = "1.3"
itertools = "0.9"
chrono = "0.4"
structopt = "0.3"
serde_json = "1.0"
paste = "0.1"
